### PR TITLE
[ALSA] Improve stream setup parameters.

### LINKED ISSUE #369: Problem with playback under arch linux.
Hi

When trying out the latest master I get.

```
cargo run --example beep
warning: field is never used: `can_pause`
   --> src/host/alsa/mod.rs:501:5
    |
501 |     can_pause: bool,
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/examples/beep`
Error: A backend-specific error has occurred: buffer time could not be set: Invalid argument
```
I'm on arch Linux using Jack, all packages recently updated and other sound applications (Jack, pulseaudio, alsa) works as expected.

```
cargo run --example enumerate
warning: field is never used: `can_pause`
   --> src/host/alsa/mod.rs:501:5
    |
501 |     can_pause: bool,
    |     ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

   Compiling cpal v0.11.0 (/home/pln/rust/adder/cpal)
    Finished dev [unoptimized + debuginfo] target(s) in 1.92s
     Running `target/debug/examples/enumerate`
Supported hosts:
  [Alsa]
Available hosts:
  [Alsa]
ALSA
  Default Input Device:
    Some("default")
  Default Output Device:
    Some("default")
  Devices: 
  1. "jack"
    Default input stream format:
      Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }
    All supported input stream formats:
      1.1. SupportedFormat { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), data_type: F32 }
    Default output stream format:
      Format { channels: 2, sample_rate: SampleRate(44100), data_type: F32 }
    All supported output stream formats:
      1.1. SupportedFormat { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), data_type: F32 }
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
  2. "hdmi:CARD=HDMI,DEV=0"
Error: DeviceNotAvailable
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
```

I have a similar setup on my laptop, arch, Jack etc. And there it works, so either my setup is wrong, or I hit a bug in `cpal`.

Any thoughts/ideas. What to try next?

### LINKED ISSUE #391: Problem when setting buffer time (alsa backend)
Continuing from #247, I'm still getting the problem (the story is I removed the set_buffer call but it was re-introduced as it created unacceptable latency). I've implemented dumping the `HwParams` (code below) and to be honest it looks like a bug in the ALSA driver for my sound card. I have an idea to make it work on my setup - that is to try to set the buffer time, and just to leave it unconstrained if there is an error setting it. I'll knock up a PR with the idea in it.

<details>
<summary>Code to implement `Debug` for `HwParams`</summary>

```rust
impl fmt::Debug for HwParams {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        unsafe {
            match dump_alsa(|outputp| alsa::snd_pcm_hw_params_dump(self.0, outputp) == 0) {
                Some(msg) => write!(f, "HwParams({})", msg),
                None => f.write_str("HwParams")
            }
        }
    }
}

/// output of dump_fn should be whether the function ran successfully (false means an error)
unsafe fn dump_alsa(dump_fn: impl FnOnce(*mut alsa::snd_output_t) -> bool) -> Option<String> {
    let mut outputp: *mut alsa::snd_output_t = ptr::null_mut();
    if let Err(e) = check_errors(alsa::snd_output_buffer_open(&mut outputp)) {
        return None;
    }
    if ! dump_fn(outputp) {
        return None;
    }
    let mut output_cstr: *mut libc::c_char = ptr::null_mut();
    let len = alsa::snd_output_buffer_string(outputp, &mut output_cstr);
    // be careful to drop this before any mutating calls to outputp
    let output_cstr: &[u8] = std::slice::from_raw_parts(output_cstr as *const u8, len);
    Some(String::from_utf8_lossy(output_cstr).into_owned())
}
```
</details>

### LINKED ISSUE #432: [Alsa Host] Start threshold of 0
I noticed that currently the start threshold is set to 0 frames:

https://github.com/RustAudio/cpal/blob/b177bcdf22be548763c6bab2ffc83415eb343151/src/host/alsa/mod.rs#L910

Now this doesn't seem like a good idea to me. I don't think this has well defined behaviour across devices and it also seems counter intuitive, to start recording/playing before there are any frames. For playback that threshold should probably be the buffer size, while for recording a single frame would work and the resulting semantics would be the same.

Using significantly less than the buffer size for playback could result in underruns (Which lead to all kinds of fun), though with the alsa host's current approach to buffering - "Just use whatever the device uses or well 100ms is okay I guess" - that can still happen for certain applications. Luckily #401 will change that). Now a period size (Or even a single frame) would also work, but it's risky. If an application relies on the buffer, because the source is bursting or can just about make the period time, not filling up the buffer before starting will result in underruns and no amount of changing the buffer size will fix that if the start_threshold is not appropriately set.

EDIT: The alsa pcm example uses a period less then a full buffer. I guess that would work as well.

### PR DESCRIPTION
**Pull request by alexmoon**
* Always set period before setting buffer size, even if `BufferSize::Fixed`.
* Set `start_threshold` based on `alsa::Direction` to avoid underruns on playback streams.

Also refactor the return values of the set params functions to reflect their actual use and resolve some clippy warnings (including a logic error in `stream_timestamp()`).

This pull request incorporates the changes from @sniperrifle2004 in #433 and #431. Based on that it should fix #369, fix #391 and fix #432.

### CODE REVIEW

**Comment by alexmoon** [comment]
@mitchmindtree I think this PR is ready to merge. Let me know if you see anything blocking it.

**Comment by strohel** [comment]
Hi, what is the status of this? It seems that merging this would unblock progress outlined in https://github.com/RustAudio/cpal/issues/495#issuecomment-750918795, which would help our adoption of `cpal`.

**Comment by est31** [comment]
This PR has a conflict. I am ready to merge it but they need to be resolved.

**Comment by strohel** [comment]
> This PR has a conflict. I am ready to merge it but they need to be resolved.

The conflict was easy to resolve, but I cannot push to @alexmoon's branch. Let's give Alex a bit more time to react.

In any case the rebased branch is at https://github.com/RustAudio/cpal/compare/master...strohel:alsa-setup

**Comment by est31** [comment]
@strohel I've turned your branch into a PR over at #582 . Closing in favour of that PR.

**Pull request closed without merging**
