### PR TITLE
Use bindgen to generate alsa-sys bindings

### PR DESCRIPTION
**Pull request by mitchmindtree**
While working on #363 I noticed I was missing a few items from the ALSA
lib. Rather than adding them by hand, I thought I would update the crate
using the latest version of bindgen. I'm on the NixOS unstable channel
and have used the `alsaLib.dev` package headers as the source for
bindings generation.

I noticed that bindgen also generated the parts of `libc` that we were
using, so I removed the `libc` dep in favour of the generated bindings.
I'm not sure what the best-practise approach is here - that is, whether
it is better to use `libc` where possible, or to use what bindgen gives
us. rust-bindgen itself doesn't give us an option to use `libc`, so I
think you'd have to use some extensive black/white-listing to get it
working.

There are a few warnings in the generated bindings related to u128 types
having an unstable ABI. This seems to be a bug in
rust-lang/rust-bindgen#1560. Rather than fixing this by hand I'd prefer
to regenerate the bindings once the bug has been fixed.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
I've [posted to the rust forums](https://users.rust-lang.org/t/best-practice-when-working-with-rust-bindgen-and-libc/38071) in order to get some feedback on best practice when working with `rust-bindgen` and `libc`.

cc @Ralith from memory you're also on Linux - would you mind having a quick look / sharing your thoughts on this PR?

**Comment by Ralith** [comment]
I think best practice here is to use whitelisting and rely on std or libc for definitions originating outside the lib being bound. This helps keep the total amount of code rustc has to digest down. It seems like `snd.*` should get us pretty far whitelistwise. I also find it pretty confusing to see things like `alsa::close` when it's actually not an alsa function.

**Comment by mitchmindtree** [comment]
Thanks for the feedback @Ralith! I've have a go at your suggestions tomorrow. I think I'll include the script used to generate the bindings in the `alsa-sys` directory as well to make it a little easier for folks to keep up to date in the future too.

**Comment by mitchmindtree** [comment]
Coming back to this after a long-winded side-track! I think for now it's best to halt work on this until #386 is resolved.

**Comment by mitchmindtree** [comment]
Closing in favour of #386.

**Pull request closed without merging**
