### PR TITLE
Add NetBSD support

### PR DESCRIPTION
**Pull request by 0323pin**
Tested on NetBSD-current (development branch, 9.99.100)
Built with Rust-1.64.0

Tests work and output sound.

### CODE REVIEW

**Review by Ralith — APPROVED** [review]
That easy, huh? Nice!

**Comment by 0323pin** [comment]
> That easy, huh? Nice!

Well, yes. Installed `alsa-lib` and `alsa-plugins-oss`, configured `~/.asoundrc` and told `cargo` where to find `libasound.so` at compile time.

**Comment by 0-wiz-0** [comment]
I'd like to see this merged, please. It's an easy change and improves the lives of NetBSD users :)

**Comment by est31** [comment]
It seems that this has caused CI to faill. @0323pin would it be possible to file a PR with rustfmt that fixes the failure?

**Comment by 0323pin** [comment]
@est31 I'll look into it and get back to you.

**Comment by 0323pin** [comment]
@est31 Hopefully fixed now, https://github.com/RustAudio/cpal/pull/705
Let me know otherwise.
Thanks!

**Pull request merged**
