### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by remilauzier**

### CODE REVIEW

**Review by est31 — CHANGES_REQUESTED** [review]
Can you remove the a.b.c → a.b.d changes? Those serve no purpose and only add noise.

**Comment by remilauzier** [comment]
I am not sure what you are talking about, but I already squash all my commit to one. Or do you talk about the number like that: ``dependency = "0.2"`` instead of ``dependency = "0.2.2"``

**Comment by est31** [comment]
@remilauzier yeah those aren't neccessary.

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
