### PR TITLE
Remove once_cell dependency

### PR DESCRIPTION
**Pull request by james7132**
Removes the `once_cell` dependency, using `std::sync::OnceLock` instead.

This bumps the MSRV of the crate from 1.60 to 1.70. Given that #277 is currently unresolved, is this acceptable?

### CODE REVIEW

**Comment by est31** [comment]
I think this is a little bit *too* soon. 1.70 was released June 1st, we should wait at least until mid/end of december.

**Comment by adsick** [comment]
mid of december has come)

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
there seems to be CI failure. @james7132 could you have a look?

**Comment by james7132** [comment]
The new CI failures seem to be unrelated.

**Comment by est31** [comment]
Regarding the CI failures, see #810

**Pull request merged**
