### PR TITLE
Add cargo-publish job

### PR DESCRIPTION
**Pull request by Luni-4**
This PR runs `cargo-publish`. 

To create the `CRATESIO_TOKEN`, you need to follow this [guide](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by est31** [comment]
@tomaka could you set up the secret as explained in the link above? I only see you as the crates.io owner of this crate.

**Comment by tomaka** [comment]
I don't have access to the settings of this repo.

**Comment by est31** [comment]
And I don't have publish rights on crates.io :)

Could you you run `cargo owner --add github:rustaudio:cratesio-publish`? Not sure though if it works if you're not part of the github team.

**Comment by est31** [comment]
@tomaka you should have admin rights now on this repo.

**Comment by tomaka** [comment]
> Not sure though if it works if you're not part of the github team.

> error: failed to invite owners to crate cpal: api errors (status 200 OK): only members of a team can add it as an owner

**Comment by tomaka** [comment]
I'm not sure I want to put my token in the settings of cpal, as this gives access to *all* my crates.
If I'm actively working on a repo, that's fine, as I might notice a PR that messes up with that.

However, now, anyone within the RustAudio orga could force push something to master and publish a new version of any of my crates.

**Comment by est31** [comment]
I see your problem. I guess the issue is https://github.com/rust-lang/crates.io/issues/849 .

What about I create a cpal maintainers team that I add you to and then you add crates.io publish rights? Then anyone in that team could publish to crates.io, but they have to do it manually.

**Comment by Luni-4** [comment]
Where was the token saved in` travis`? Perhaps it could be possible to recreate the same situation. If you would describe the steps, I could change the Github Actions script.

**Comment by est31** [comment]
Another alternative is creating a separate github account.

**Comment by est31** [comment]
@Luni-4 my hands are bound. Only owner of cpal is still tomaka: https://crates.io/crates/cpal

**Comment by Luni-4** [comment]
> @Luni-4 my hands are bound. Only owner of cpal is still tomaka: https://crates.io/crates/cpal

I see. So let's wait for @tomaka decision then :)

**Comment by est31** [comment]
Alright, I've added a new github account @rustaudio-publish-bot . Also I've created a new team @RustAudio/cpal-maintainers which tomaka is now a member of.

@tomaka can you try running `cargo owner --add github:rustaudio:cpal-maintainers` for the cpal crate? Then the bot account will be allowed to publish cpal to crates.io and we can use its token in this PR. The bot account will only ever have access to RustAudio crates so its impact will be limited.

**Comment by tomaka** [comment]
@est31 Done!

**Comment by est31** [comment]
@tomaka wonderful, thank you! Now everything should be set up. Let's hope it works.

**Comment by Luni-4** [comment]
Thank you @est31 and @tomaka! :)

**Comment by est31** [comment]
@tomaka could you also add the team for the `alsa-sys` crate? It's in the same repo as this one.

**Comment by tomaka** [comment]
Done.

**Pull request merged**
