### PR TITLE
clippy fixes

### PR DESCRIPTION
**Pull request by xMAC94x**

### CODE REVIEW

**Comment by xMAC94x** [comment]
@est31  those are some clippy improvements, that where quite easy to improve :). ping

**Comment by xMAC94x** [comment]
can we give each thread a UNIQUE name. in our game veloren we have 80 threads, created by many different libs, and we want a way to easier debug what thread is doing what. a thread name would help alot here.

**Comment by xMAC94x** [comment]
(some ci check seems to fail, but it worked in a run before)

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
