### PR TITLE
Update windows-rs dependency

### PR DESCRIPTION
**Pull request by paul-hansen**
Just attempting to get Bevy's dependencies to all use the same windows crate version again. Lmk if you want any changes. Thanks!

### CODE REVIEW

**Review by est31 — APPROVED** [review]
Looks great, but waiting for CI to work. Also maybe it might make sense to directly make a release from this PR.

**Comment by paul-hansen** [comment]
I get a similar `Installer hash does not match.` error downloading it from winget too, tried multiple previous versions of asio4all as well. Not seeing a place to contact asio4all to report the issue.

**Comment by est31** [comment]
@paul-hansen the github account I pinged above belongs to the maintainer of the [package on chocolatey](https://community.chocolatey.org/packages/asio4all), they hopefully know more.

**Comment by joachimschmidt557** [comment]
Hi, maintainer of the `asio4all` chocolatey package here :wave: . It seems that the download URL and checksum of ASIO4ALL has changed. I submitted an [updated version of the package](https://community.chocolatey.org/packages/asio4all/2.15.20230722). It should take some days until the new package version is approved.

Thanks for notifying me of the issue with the package!

**Comment by joachimschmidt557** [comment]
The [updated version](https://community.chocolatey.org/packages/asio4all/2.15.20230722) of the chocolatey package has been approved and will be the default version when installed. Feel free to let me know if any further issues with the package arise in future 👍

**Comment by est31** [comment]
@joachimschmidt557 thanks for the quick help! Now I can merge this.

**Pull request merged**
