### PR TITLE
Add Github Actions

### LINKED ISSUE #318: Appveyor is broken
It seems that since the ownership transfer, appveyor has been broken.

Since Aug 10, these errors are being returned by the webhook:

```
{"message":"PR and project repositories do not match."}
```

See also https://github.com/appveyor/ci/issues/449

Not sure how to fix this.

### PR DESCRIPTION
**Pull request by Luni-4**
This PR adds the `Github Actions` CI system to `cpal`.

The `cpal.yml` script is structured in this way:

1. An action that runs `cargo clippy` on the repository code and shows the obtained results as annotations. It works both with the `push` and `pull_request` events

2. A job that runs `all-features` and `no-default-features` tests on `Ubuntu`

3. A job that builds the `beep` example using both the `asmjs-unknown-emscripten` and `wasm32-unknown-emscripten` targets

4. A job that runs `all-features` and `no-default-features` tests on `Windows` 32 and 64 bit

As suggested by @est31, I've removed the old CI systems and updated the build badge. 

As for the `cargo publish` job proposed by @ishitatsuyuki, I will create another PR once this one will be merged.

This PR also fixes #318 

If you want some changes, I will try to implement them as soon as possible.

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by Luni-4** [comment]
@est31 
Forgot to mention that this PR closes #9 too.

**Comment by est31** [comment]
Hmmm due to this clippy job it seems to fail: https://github.com/RustAudio/cpal/commit/8f5496b0fd15601eace35b238e6fcf1594784e9a/checks?check_suite_id=250545693

@Luni-4 could you make a PR to mark the clippy stuff as allow-fail?

**Comment by Luni-4** [comment]
@est31 
Yep, it failed because `clippy` found an error in the code: [https://github.com/RustAudio/cpal/runs/247037545](https://github.com/RustAudio/cpal/runs/247037545)

Hmm, I would recommend to fix the error in the code instead of marking the `clippy-action` as allow-fail, but I can do it if you think it's extremely necessary.

**Comment by est31** [comment]
It's complaining about ridiculous stuff like "casting u16 to f32 may become silently lossy if you later change the type"...

As for fixing that one error, sure go ahead. In general many of the warnings are ridiculous and also we shouldn't change code around too much until #301 is merged.

**Comment by Luni-4** [comment]
> It's complaining about ridiculous stuff like "casting u16 to f32 may become silently lossy if you later change the type"...
> 
> As for fixing that one error, sure go ahead. In general many of the warnings are ridiculous and also we shouldn't change code around too much until #301 is merged.

I agree, but it doesn't fail for warnings, only for errors. So when the error will be fixed, the repository will get back green again :)

**Comment by est31** [comment]
@Luni-4 it's shown for pull requests, no? It fails for contributor prs without the contributors having done anything wrong.

**Comment by Luni-4** [comment]
> @Luni-4 it's shown for pull requests, no? It fails for contributor prs without the contributors having done anything wrong.

@est31 Yep, it works for PRs too. I will try to fix it as soon as possible then

**Pull request merged**
