### PR TITLE
Re-enable WasApi loopback capture

### PR DESCRIPTION
**Pull request by dheijl**
See issue #476.

This is essentially PR #339 again which was merged but was later (accidentally?) removed again.

It allows loopback capture from a WasApi output device.

### CODE REVIEW

**Comment by dheijl** [comment]
Is anything holding this back?

**Comment by mitchmindtree** [comment]
So sorry about the delay @dheijl - only my limited access to windows is holding this one back! I'll land this as it seems pretty straight forward, and we don't seem to be getting any further reviews from Windows folk other than that thumbs up.

**Comment by Boscop** [comment]
@dheijl How can I actually open a loopback device? 
I can't find anything about loopback devices in the cpal docs.

**Comment by dheijl** [comment]
It is automatic when you capture audio from the output device.

This is from swyh-rs (https://github.com/dheijl/swyh-rs/blob/master/src/main.rs):

```rust
/// capture_audio_output - capture the audio stream from the default audio output device
///
/// sets up an input stream for the wave_reader in the appropriate format (f32/i16/u16)
fn capture_output_audio(device: &cpal::Device) -> Option<cpal::Stream> {
    log(format!(
        "Capturing audio from: {}",
        device
            .name()
            .expect("Could not get default audio device name")
    ));
    let audio_cfg = device
        .default_output_config()
        .expect("No default output config found");
    log(format!("Default audio {:?}", audio_cfg));
    match audio_cfg.sample_format() {
        cpal::SampleFormat::F32 => match device.build_input_stream(
            &audio_cfg.config(),
            move |data, _: &_| wave_reader::<f32>(data),
            capture_err_fn,
        ) {
            Ok(stream) => Some(stream),
            Err(e) => {
                log(format!("Error capturing f32 audio stream: {}", e));
                None
            }
        },
        cpal::SampleFormat::I16 => {
            match device.build_input_stream(
                &audio_cfg.config(),
                move |data, _: &_| wave_reader::<i16>(data),
                capture_err_fn,
            ) {
                Ok(stream) => Some(stream),
                Err(e) => {
                    log(format!("Error capturing i16 audio stream: {}", e));
                    None
                }
            }
        }
        cpal::SampleFormat::U16 => {
            match device.build_input_stream(
                &audio_cfg.config(),
                move |data, _: &_| wave_reader::<u16>(data),
                capture_err_fn,
            ) {
                Ok(stream) => Some(stream),
                Err(e) => {
                    log(format!("Error capturing u16 audio stream: {}", e));
                    None
                }
            }
        }
    }
}

/// capture_err_fn - called whan it's impossible to build an audio input stream
fn capture_err_fn(err: cpal::StreamError) {
    log(format!("Error {} building audio input stream", err));
}
```

**Pull request merged**
