### PR TITLE
Replace stdweb with wasm-bindgen, js-sys, and web-sys

### LINKED ISSUE #518: RUSTSEC-2020-0056: stdweb: stdweb is unmaintained
The stdweb crate is unmaintained, as recorded by [this RustSec advisory](https://rustsec.org/advisories/RUSTSEC-2020-0056.html). Here is the [reference issue](https://github.com/koute/stdweb/issues/403). 

Maintained alternatives include wasm-bindgen, js-sys, and web-sys.

I'm willing to look into this and see how difficult it is. I'm also willing to attempt it and open a pull request if it would be accepted.

### PR DESCRIPTION
**Pull request by brightly-salty**
Replaces stdweb (which is unmaintained) with a combination of wasm-bindgen, and js-sys web-sys (which are). Fixes #518.

### CODE REVIEW

**Comment by brightly-salty** [comment]
@mitchmindtree 

This is now ready for review. I strongly recommend to squash while merging due to the many failing commits. Let me know if you need me to do anything else.

**Comment by est31** [comment]
There is a build failure.

**Comment by brightly-salty** [comment]
Yeah,  I need to get back into the code and actually fix the merge conflict. I'm not sure why the ios build fails though

**Comment by est31** [comment]
ios fails on master too, so it's not a regression of this PR, so there is no requirement to fix it in here.

**Comment by ishitatsuyuki** [comment]
@brightly-salty Is there anything left in this PR that you consider unfinished? I look forward to merging this PR soon if there are no known issues, given that asmjs CI appears to be broken on master.

**Comment by brightly-salty** [comment]
@ishitatsuyuki I'll look into it, but if I remember correctly there was some functionality in main that couldn't be fully matched with the replacement library.

**Comment by mbodmer** [comment]
This issue would probably fix the asmjs-wasm32 checks

**Comment by est31** [comment]
The PR also needs a rebase. It's a good idea, and I like the direction of it.

**Comment by brightly-salty** [comment]
If there is still interest in this PR in general, the rebase would be very messy I think. It might be easier to close this and start over with the newest versions of the replacement crates, since they probably have newer functionality I couldn't take into account 2 years ago.

**Comment by est31** [comment]
Okay let's close this then :+1: .

**Pull request closed without merging**
