### PR TITLE
Fix compilation error when using null host

### PR DESCRIPTION
**Pull request by exrook**
Also remove other references to EventLoop

### CODE REVIEW

**Comment by est31** [comment]
I wonder if it would be possible to set up CI for the null host? Only to do a cargo check whether it builds.

**Comment by exrook** [comment]
If each backend was a default feature flag, then compiling without default features would accomplish that (which it looks like the current CI already does). Otherwise I think we would have to have CI cross compile to a platform with no backends yet. (That's how I ran into this error, I'm looking into adding an Android backend)

**Comment by est31** [comment]
> I think we would have to have CI cross compile to a platform with no backends yet.

Sounds good! Any ideas for a platform that has an easy to set up cross compilation toolchain?

**Comment by exrook** [comment]
I think `wasm32-wasi` should work well, it doesn't pull in any of the existing backends, and the tests already run for the other wasm targets.

**Comment by est31** [comment]
@exrook could you add `wasm-wasi` CI code to this PR? That would be neat!

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
