### PR TITLE
Fix CI failure

### PR DESCRIPTION
**Pull request by 0323pin**

### CODE REVIEW

**Comment by est31** [comment]
Still fails, I think you need to either run `cargo fmt` or maybe remove the trailing spaces (there are still ones remaining).

**Comment by 0323pin** [comment]
@est31 Fixed now.
`asmjs-wasm32-test (asmjs-unknown-emscripten)` still fails but, this has nothing to do with these changes.

**Review by est31 — APPROVED** [review]

**Comment by est31** [comment]
> `asmjs-wasm32-test (asmjs-unknown-emscripten)` still fails but, this has nothing to do with these changes.

Yeah eventually it would be good to have that addressed too, but it didn't regress recently, so is less of an issue right now.

**Comment by 0323pin** [comment]
Awesome, thanks.
Now, I just need a `rodio` release using current `cpal` and I'll be able to fix the use of `rodio`-backend.

**Pull request merged**
