### PR TITLE
Turn off std feature of failure

### PR DESCRIPTION
**Pull request by est31**
This saves us some dependencies and thus speeds up the build.

### CODE REVIEW

**Comment by est31** [comment]
Cargo tree before:

```
cpal v0.10.0 (~/src/cpal)
├── alsa-sys v0.1.1 (~/src/cpal/alsa-sys)
│   └── libc v0.2.60
│   [build-dependencies]
│   └── pkg-config v0.3.15
├── failure v0.1.5
│   ├── backtrace v0.3.34
│   │   ├── backtrace-sys v0.1.31
│   │   │   └── libc v0.2.60 (*)
│   │   │   [build-dependencies]
│   │   │   └── cc v1.0.38
│   │   ├── cfg-if v0.1.9
│   │   ├── libc v0.2.60 (*)
│   │   └── rustc-demangle v0.1.15
│   └── failure_derive v0.1.5
│       ├── proc-macro2 v0.4.30
│       │   └── unicode-xid v0.1.0
│       ├── quote v0.6.13
│       │   └── proc-macro2 v0.4.30 (*)
│       ├── syn v0.15.43
│       │   ├── proc-macro2 v0.4.30 (*)
│       │   ├── quote v0.6.13 (*)
│       │   └── unicode-xid v0.1.0 (*)
│       └── synstructure v0.10.2
│           ├── proc-macro2 v0.4.30 (*)
│           ├── quote v0.6.13 (*)
│           ├── syn v0.15.43 (*)
│           └── unicode-xid v0.1.0 (*)
├── lazy_static v1.3.0
├── libc v0.2.60 (*)
└── num-traits v0.2.8
    [build-dependencies]
    └── autocfg v0.1.5
[dev-dependencies]
└── hound v3.4.0
```

Cargo tree after:

```
cpal v0.10.0 (~/src/cpal)
├── alsa-sys v0.1.1 (~/src/cpal/alsa-sys)
│   └── libc v0.2.60
│   [build-dependencies]
│   └── pkg-config v0.3.15
├── failure v0.1.5
│   └── failure_derive v0.1.5
│       ├── proc-macro2 v0.4.30
│       │   └── unicode-xid v0.1.0
│       ├── quote v0.6.13
│       │   └── proc-macro2 v0.4.30 (*)
│       ├── syn v0.15.43
│       │   ├── proc-macro2 v0.4.30 (*)
│       │   ├── quote v0.6.13 (*)
│       │   └── unicode-xid v0.1.0 (*)
│       └── synstructure v0.10.2
│           ├── proc-macro2 v0.4.30 (*)
│           ├── quote v0.6.13 (*)
│           ├── syn v0.15.43 (*)
│           └── unicode-xid v0.1.0 (*)
├── lazy_static v1.3.0
├── libc v0.2.60 (*)
└── num-traits v0.2.8
    [build-dependencies]
    └── autocfg v0.1.5
[dev-dependencies]
└── hound v3.4.0
```

I count 5 deps saved.

**Comment by ishitatsuyuki** [comment]
I don't really like this. Compilation time is not a bottleneck for cpal (unlike Amethyst), and it's likely that failure's std feature is also enabled by other dependencies of downstream users.

**Comment by est31** [comment]
@ishitatsuyuki it's not a bottleneck but the faster it compiles the better :).

This PR is also one of the alternatives that we can take if we want to provide a MSRV guarantee: #277

@ishitatsuyuki what would you think about removing the std feature only from the dependencies but not the dev-dependencies? Then the changes of the examples wouldn't be needed.

**Comment by ishitatsuyuki** [comment]
Yes, I’m fine that way.

**Comment by est31** [comment]
Hmm seems this won't help us with the MSRV stuff because cargo is stupid (cargo build still includes it). It will help reverse dependencies of cpal but most of them already include full failure from another place. The only place it helps is reverse dependencies that don't use failure otherwise like e.g. rodio. I don't think this PR is worth this little improvement. If anyone disagrees I'll reopen.

**Pull request closed without merging**
